custom:
  - "https://github.com/root28root/move-projects/issues/new?template=hire-me.yml"
  - "mailto:007rootmhz@gmail.com"
  - "https://discord.com/users/1047911417396875264"
  - "https://t.me/Nikolai_Rootmhz"
