blank_issues_enabled: false
contact_links:
  - name: Telegram
    url: https://t.me/Nikolai_Rootmhz
    about: DM me for quick scoping or questions.
  - name: Email
    url: mailto:007rootmhz@gmail.com
    about: Email me for a quick estimate.
