[package]
name = "Escrow"
version = "0.0.1"
authors = ["Rootmhz"]

[addresses]
Escrow = "0x0"

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move", subdir = "language/move-stdlib", rev = "main" }
