name: Move Build & Test (Aptos)
on: [push, pull_request]

jobs:
  move:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get install -y curl python3

      - name: Install Aptos CLI
        run: |
          curl -fsSL https://aptos.dev/scripts/install_cli.py | python3
          aptos --version

      # Compile each package with Aptos Move compiler
      - name: Compile MyToken
        run: |
          cd mytoken
          aptos move compile --save-metadata --bytecode-version 6

      - name: Compile Escrow
        run: |
          cd escrow
          aptos move compile --save-metadata --bytecode-version 6

      - name: Compile SimpleNFT
        run: |
          cd simplenft
          aptos move compile --save-metadata --bytecode-version 6

      # (Optional) Run tests but don't fail pipeline yet
      - name: Test MyToken (allow failure)
        run: |
          cd mytoken
          aptos move test || true

      - name: Test Escrow (allow failure)
        run: |
          cd escrow
          aptos move test || true

      - name: Test SimpleNFT (allow failure)
        run: |
          cd simplenft
          aptos move test || true
