name: Move Build & Test (Aptos)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Aptos CLI
        run: |
          curl -sSL "https://aptos.dev/scripts/install_cli.py" | python3
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          aptos --version

            - name: Static sanity checks
        run: |
          set -euo pipefail
          # 1) нет плейсхолдеров {{ADDR}} в коде проектов (игнорим build/, vendor/, .github/)
          if grep -RIn '{{ADDR}}' mytoken escrow simplenft minimarket \
               --exclude-dir=build --exclude-dir=vendor --exclude-dir=.github; then
            echo 'ERROR: found {{ADDR}} placeholders'; exit 1; fi

          # 2) в ТЕСТАХ не должно быть `use std::` (только 0x1::)
          if grep -RIn 'use std::' mytoken/tests escrow/tests simplenft/tests minimarket/tests \
               --include='*.move' --exclude-dir=build --exclude-dir=vendor --exclude-dir=.github; then
            echo 'ERROR: found std:: imports in tests; use 0x1::'; exit 1; fi


      - name: Repo-wide build & tests
        run: ./tools/check.sh
