name: Move Build & Test (Aptos)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Aptos CLI
        run: |
          curl -sSL "https://aptos.dev/scripts/install_cli.py" | python3
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          aptos --version

      - name: Repo-wide build & tests
        run: ./tools/check.sh
