name: Move Build & Test (Aptos)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Aptos CLI
        run: |
          curl -sSL "https://aptos.dev/scripts/install_cli.py" | python3
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          aptos --version

- name: Static sanity checks
  run: |
    set -euo pipefail
    ! grep -RIn "{{ADDR}}" -- . || (echo "ERROR: found {{ADDR}} placeholders" && exit 1)
    ! grep -RIn "use std::" -- . || (echo "ERROR: found std:: imports; use 0x1::" && exit 1)

      - name: Repo-wide build & tests
        run: ./tools/check.sh
