name: Move Build & Test
on: [push, pull_request]
jobs:
  move:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config clang curl
      - name: Install Sui (prebuilt)
        run: |
          sudo apt-get update && sudo apt-get install -y libssl-dev pkg-config clang curl
          curl -L https://github.com/MystenLabs/sui/releases/latest/download/sui-linux-x86_64.tgz -o sui.tgz
          tar -xzf sui.tgz
          chmod +x sui
          sudo mv sui /usr/local/bin/sui
          which sui
          sui --version
      - name: Build MyToken
        run: |
          cd mytoken && sui move build
      - name: Test MyToken (allow failure for now)
        run: |
          cd mytoken && sui move test || true
      - name: Build Escrow
        run: |
          cd escrow && sui move build
      - name: Test Escrow (allow failure for now)
        run: |
          cd escrow && sui move test || true
      - name: Build SimpleNFT
        run: |
          cd simplenft && sui move build
      - name: Test SimpleNFT (allow failure for now)
        run: |
          cd simplenft && sui move test || true
