name: Move Build & Test (Aptos)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Aptos CLI
        run: |
          curl -sSL "https://aptos.dev/scripts/install_cli.py" | python3
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          aptos --version

      - name: Static sanity checks
        run: |
          set -euo pipefail
          # 1) нет плейсхолдеров {{ADDR}} (игнорим build/ и vendor/)
          if grep -RIn --exclude-dir=build --exclude-dir=vendor '{{ADDR}}' .; then
            echo 'ERROR: found {{ADDR}} placeholders'; exit 1; fi
          # 2) в ТЕСТАХ не должно быть use std:: (игнорим build/ и vendor/)
          if ls */tests/*.move >/dev/null 2>&1; then
            if grep -RIn --include='*.move' --exclude-dir=build --exclude-dir=vendor 'use std::' */tests; then
              echo 'ERROR: found std:: imports in tests; use 0x1::'; exit 1; fi
          fi

      - name: Repo-wide build & tests
        run: ./tools/check.sh
