name: Release Artifacts (Aptos)

on:
  push:
    tags: ["v*"]

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Aptos CLI
        run: |
          curl -sSL "https://aptos.dev/scripts/install_cli.py" | python3
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          aptos --version
      - name: Build all projects
        run: ./tools/check.sh
      - name: Package artifacts
        run: |
          mkdir -p dist
          for p in mytoken escrow simplenft minimarket; do
            (cd "$p" && aptos move compile)
            zip -r "dist/${p}-build.zip" "$p/build"
          done
      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
