name: Release

on:
  push:
    tags:
      - 'v*'        # сработает при пуше тега v0.2.0, v1.0.0 и т.п.

permissions:
  contents: write   # чтобы создавать релизы

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # (опционально) прогнать сборку/тесты перед релизом
      # - name: Build & test
      #   run: ./tools/check.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}  # v0.2.0
          generate_release_notes: true
          body: |
            v0.2.0 — Vesting + PaySplit; docs; CI hardening
            See CHANGELOG.md for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
